schema_version = "1.0.0"

id = "node_pinyin"
version = "0.0.1"
name = "szm/首字母"
tagline = "Enable node search with PinYin/支持节点中文拼音搜索"
maintainer = "Xinyu Zhu(异次元学者) xzhuah77@gmail.com"
type = "add-on"
tags = ["Node", "Geometry Nodes"]
blender_version_min = "4.2.0"
license = [
    "SPDX:GPL-3.0-or-later",
]
